/* Icones de monstres, recoltees par
   tools/recolter_bestiary_icones.py depuis le bestiaire du wiki
   communautaire mistfallhunter.wikitactics.com/bestiary/. Fichiers
   dans site/icones_monstres/. NE PAS EDITER A LA MAIN.

   Nom de monstre -> nom de fichier local, associes par le
   `data-name` du tableau, jamais par position. Un monstre absent
   d'ici n'a pas d'icone connue -- le site retombe sur un point
   uni, pas une icone inventee. */
window.D_ICONES_MONSTRES = {"Berserker":"berserker.png","Blackplume Priest":"blackplume-priest.png","Blister Wasp":"blister-wasp.png","Brandrgarde Captain":"brandrgarde-captain.png","Clawslave":"clawslave.png","Corroded Archer":"corroded-archer.png","Corroded Guard":"corroded-guard.png","Corroded Soldier":"corroded-soldier.png","Eeryl":"eeryl.png","Eeryl Hatchling":"eeryl-hatchling.png","Elite Berserker":"elite-berserker.png","Elite Corroded Archer":"elite-corroded-archer.png","Elite Corroded Priest":"elite-corroded-priest.png","Elite Corroded Soldier":"elite-corroded-soldier.png","Elite Lizardfolk Warrior":"elite-lizardfolk-warrior.png","Flesheater":"flesheater.png","Foul Hound":"foul-hound.png","Foul Hound Alpha":"foul-hound-alpha.png","Frenzied Wizard":"frenzied-wizard.png","Fungus Matron":"fungus-matron.png","General Harald":"general-harald.png","General's Guard":"generals-guard.png","Golden Sprite":"golden-sprite.png","Guard":"guard.png","Gylden Corroded Soldier":"gylden-corroded-soldier.png","Hallowgrove Woodling":"hallowgrove-woodling.png","Intrush":"intrush.png","Lamplighter":"lamplighter.png","Lizardfolk Priest":"lizardfolk-priest.png","Lizardfolk Soldier":"lizardfolk-soldier.png","Nightwatcher":"nightwatcher.png","Parading Corpse":"parading-corpse.png","Penitent":"penitent.png","Returner Woodling":"returner-woodling.png","Sacred Chamber Priest":"sacred-chamber-priest.png","Silverscale Striker":"silverscale-striker.png","Soulgnawer":"soulgnawer.png","Soulreaver Acolyte":"soulreaver-acolyte.png","Soulreaver Servitor":"soulreaver-servitor.png","Spear Bandit":"spear-bandit.png","Strawer":"strawer.png","Strawer Chief":"strawer-chief.png","Sálmar, the Cursed Moonwane":"salmar-the-cursed-moonwane.png","Twinblade Warrior Statue":"twinblade-warrior-statue.png","Tyrannical Executioner":"tyrannical-executioner.png"};
